#Python data analysis----pandas

#panel data-----pandas

#pandas are used to work with datasets
#anlythe the data sets

In [24]:
import pandas as pd

#Series-> one dimentional labeled array, of mixed data types(hetrogeneous data allows)

In [25]:
x=pd.Series([1,2,3,4])
print(x)

0    1
1    2
2    3
3    4
dtype: int64

In [26]:
#acess 3 in the series
print(x[2])
print(x[0])

3
1

In [27]:
x.index.name='index'
print(x)

index
0    1
1    2
2    3
3    4
dtype: int64

In [28]:
a=[1,2,3,4]
my_var=pd.Series(a, index=['a','b','c','d'])
my_var.index.name='index'
print(my_var)

index
a    1
b    2
c    3
d    4
dtype: int64

In [29]:
#acess elements with new labels

print(my_var['c'])
print(my_var['a'])

3
1

#pass dictionaries in series

In [30]:
dict1={'day1':100,'day2':200,'day3':150}
my_var1=pd.Series(dict1)
print(my_var1)

day1    100
day2    200
day3    150
dtype: int64

In [31]:
dict2={'a':1,'b':2,'c':'three'}
x=pd.Series(dict2)
print(x)

a        1
b        2
c    three
dtype: object

In [32]:
#we are not able to pass lst like this
lst=[('a',1),('b',2),('c',3)]
y=pd.Series(lst)
print(y)

0    (a, 1)
1    (b, 2)
2    (c, 3)
dtype: object

In [33]:
#avoid printing dtype in your series

data=[1,2,3,4,5,6]
x=pd.Series(data)
print(x.to_string(index=False,dtype=False))
#to_string-->to print the full data in series

1
2
3
4
5
6

#DataFarame -----> 2 dimentional labeled data--in the form of rows and columns

In [34]:
data={
    'name':['hari','pavani','mythili','manobi'],
    'age':[20,23,25,27],
    'gender':['m','f','f','m']
}

df=pd.DataFrame(data, index=['fst','second','thrd','fourth'])
#df.index.name='index'
print(df)

           name  age gender
fst        hari   20      m
second   pavani   23      f
thrd    mythili   25      f
fourth   manobi   27      m

In [35]:
df['age']

fst       20
second    23
thrd      25
fourth    27
Name: age, dtype: int64

In [36]:
df.loc['second']

name      pavani
age           23
gender         f
Name: second, dtype: object

In [37]:
data=[('john',23,'m'),('bob','22','m'),('alice',22,'m')]
df=pd.DataFrame(data, columns=['Name','Age','Gender'])
print(df)

    Name Age Gender
0   john  23      m
1    bob  22      m
2  alice  22      m

In [38]:
#getting the data from ---column wise

print(df['Name'])

0     john
1      bob
2    alice
Name: Name, dtype: object

In [39]:
#getting the data from ---row wise
print(df.loc[1])

Name      bob
Age        22
Gender      m
Name: 1, dtype: object

In [40]:
#getting multiple elements by using loc
print(df.loc[1:2])

    Name Age Gender
1    bob  22      m
2  alice  22      m

In [41]:
df

    Name Age Gender
0   john  23      m
1    bob  22      m
2  alice  22      m

In [42]:
print(df.loc[1,'Age'])

22

In [43]:
print(df.loc[2,'Name'])

alice

#Data set importing

In [44]:
import pandas as pd
data=pd.read_csv('/content/netflix_titles.csv')
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [45]:
"""custom=data.to_string(index=False)
print(custom)"""
#to print whole data

'custom=data.to_string(index=False)\nprint(custom)'

Handson part

In [46]:
#1

lst=[1,2,3,4,5]
tupl=(1,2,3,4,5)

index=['a','b','c','d','e']

x=pd.Series(lst, index=index)
y=pd.Series(tupl, index=index)
print(x)
print(y)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [47]:
"""set1={1,2,3,4,5}
z=pd.Series(set1, index=index)
print(z)"""
#it will throw error-------> we cant use set directly in series---> convert set to lst and than use

set1={1,2,3,4,5}
z=pd.Series(list(set1), index=index)
print(z)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [48]:
#2.

dict1={'vijay':'sharma','mounika':'bopperla','sunkar':'sundhar'}

x=pd.Series(dict1)
print(x)

vijay        sharma
mounika    bopperla
sunkar      sundhar
dtype: object

#converting the series to lst, tuple, dictionary, set

In [49]:
#x=[1,2,3,4,5,6,7,8,9,10]
y=[0,1,2,3,4,5,6,7,8,9]

series=pd.Series(range(1,11), index=y)
print(series)

x=list(series)
print(x)

y=tuple(series)
print(y)

z=dict(series)
print(z)

i=set(series)
print(i)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

#operations on series

In [50]:
import numpy as np
s = pd.Series(np.random.randint(0, 50, 10))  # Changed to provide low, high, and size correctly
print(s)

0    49
1    42
2    21
3    35
4    30
5     1
6    25
7    22
8    49
9    16
dtype: int64

In [51]:
#print fst 5 elements
print(s.head(5))
print(s[0:5])

0    49
1    42
2    21
3    35
4    30
dtype: int64
0    49
1    42
2    21
3    35
4    30
dtype: int64

In [52]:
#print last 5 elements
print(s.tail(5))
print(s[-5:])

5     1
6    25
7    22
8    49
9    16
dtype: int64
5     1
6    25
7    22
8    49
9    16
dtype: int64

In [53]:
#acessing elements by using index
print(s[5])

1

In [54]:
#insert 5 position  to 50

s[4]=50
print(s)

0    49
1    42
2    21
3    35
4    50
5     1
6    25
7    22
8    49
9    16
dtype: int64

In [55]:
arr1=s.drop(0)
print(arr1)

1    42
2    21
3    35
4    50
5     1
6    25
7    22
8    49
9    16
dtype: int64

In [56]:
#insert element in middile of the series without replacing the elements

x=pd.Series([1,2,3,4,6])
print(x)

0    1
1    2
2    3
3    4
4    6
dtype: int64

In [57]:
y=x[0:4]
z=x[5:]
i=pd.concat([y,pd.Series([5]),z])

print(i)

0    1
1    2
2    3
3    4
0    5
dtype: int64

In [58]:
#add element to the last of the series

x=pd.Series([1,2,3,4,5])
print(x)

"""x=x.append(pd.Series(6))
print(x)"""

x = pd.concat([x, pd.Series([6])], ignore_index=True)
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [59]:
#search element in the given series

series=pd.Series([1,2,3,4,6,5])

if 3 in series.values:
  print('yes')
else:
  print('no')

yes

In [60]:
# 6. concatenation of 2 series

series_a=pd.Series([1,2,3,4,5])
series_b=pd.Series([6,7,8,9,10])

#x=pd.concat([series_a, series_b])
x=pd.concat([series_a, series_b], ignore_index=True)
print(x)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [61]:
#7.. print all the elemnts in the series by using for loop

sample=pd.Series(range(1,11))
#print(sample)
for i in sample:
  print(i)

1
2
3
4
5
6
7
8
9
10

In [62]:
i=0
while(i< len(sample)):
  print(sample[i])
  i=i+1

1
2
3
4
5
6
7
8
9
10

In [63]:
#8..  creating dataframes from nested lst and lst

lst=[['aa','bb','cc'],['dd','ee','ff']]
dict1={'kris':['john',33],'membership':['bob',32]}

df=pd.DataFrame(lst, columns=['x','y','z'])
df1=pd.DataFrame(dict1)

print(df)
print(df1)

    x   y   z
0  aa  bb  cc
1  dd  ee  ff
   kris membership
0  john        bob
1    33         32

In [64]:
#9...

data={
    'name':['hari','pavani','mythili','manobi'],
    'age':[20,23,25,27]
}


df=pd.DataFrame(data)
df

      name  age
0     hari   20
1   pavani   23
2  mythili   25
3   manobi   27

In [65]:
df.head(3)

      name  age
0     hari   20
1   pavani   23
2  mythili   25

In [66]:
#print the data age greater than 20
print(df[df['age'] >20])

      name  age
1   pavani   23
2  mythili   25
3   manobi   27

In [67]:
data2={
    'name':['haary','pavi','manoj','mallika'],
    'age':[20,23,25,27],
}

df2=pd.DataFrame(data2)

In [68]:
"""df3=df.append(df, ignore_index=True)
print(df3)"""

df3=pd.concat([df,df2], ignore_index=True)
print(df3)

      name  age
0     hari   20
1   pavani   23
2  mythili   25
3   manobi   27
4    haary   20
5     pavi   23
6    manoj   25
7  mallika   27

In [69]:
#updating 2nd row

df3.loc[2,'name']='jacob'
df3.loc[2,'age']=24
print(df3)

      name  age
0     hari   20
1   pavani   23
2    jacob   24
3   manobi   27
4    haary   20
5     pavi   23
6    manoj   25
7  mallika   27

In [70]:
#delete the fst row from the data frame

df3=df3.drop(1)
df3

      name  age
0     hari   20
2    jacob   24
3   manobi   27
4    haary   20
5     pavi   23
6    manoj   25
7  mallika   27

In [71]:
print(df3)

      name  age
0     hari   20
2    jacob   24
3   manobi   27
4    haary   20
5     pavi   23
6    manoj   25
7  mallika   27

In [72]:
#converting data frame to lst and dictionary
lst=list(df3)
print(lst)

dic1=dict(df3)
print(dic1)

['name', 'age']
{'name': 0       hari
2      jacob
3     manobi
4      haary
5       pavi
6      manoj
7    mallika
Name: name, dtype: object, 'age': 0    20
2    24
3    27
4    20
5    23
6    25
7    27
Name: age, dtype: int64}

In [73]:
df3

      name  age
0     hari   20
2    jacob   24
3   manobi   27
4    haary   20
5     pavi   23
6    manoj   25
7  mallika   27

#split the data frame row wise and column wise

In [74]:
#split by row wise

df4=df3.iloc[ :5 , :]
df4

     name  age
0    hari   20
2   jacob   24
3  manobi   27
4   haary   20
5    pavi   23

In [75]:
df5=df3.iloc[5:,:]
df5

      name  age
6    manoj   25
7  mallika   27

In [76]:
#splitting through column

In [77]:
x=df3.iloc[:,:1]
x

      name
0     hari
2    jacob
3   manobi
4    haary
5     pavi
6    manoj
7  mallika

In [78]:
y=df3.iloc[:,1:]
y

   age
0   20
2   24
3   27
4   20
5   23
6   25
7   27

In [79]:
df3[df3['age']>23]

      name  age
2    jacob   24
3   manobi   27
6    manoj   25
7  mallika   27

In [84]:
x=df3[df3['age'] > 22]
y=x.sort_values(by='age', ascending=False)
print(y)

      name  age
3   manobi   27
7  mallika   27
6    manoj   25
2    jacob   24
5     pavi   23

In [88]:
z=list(y['age'])
print(z)

[27, 27, 25, 24, 23]

In [80]:
#sort the data frame ages in ascending order

df3.sort_values(by='age', ascending=True)

      name  age
0     hari   20
4    haary   20
5     pavi   23
2    jacob   24
6    manoj   25
3   manobi   27
7  mallika   27

In [81]:
#by descending

df3.sort_values(by='age', ascending=False)

      name  age
3   manobi   27
7  mallika   27
6    manoj   25
2    jacob   24
5     pavi   23
0     hari   20
4    haary   20

In [82]:
#storing the age values from the dataframe in the form of set

set1=set(df3['age'])
set1

{20, 23, 24, 25, 27}